---
deployment:
  tasks:
    # Define the deployment path
    - export DEPLOYPATH=/home3/avidityi/public_html/ghrproperties.id
    
    # Deploy directly from the root (since files are now at the root of the production branch)
    - /bin/cp -R . $DEPLOYPATH
    
    # Set file permissions
    - /bin/chmod 644 $DEPLOYPATH/.htaccess
    - /bin/find $DEPLOYPATH -type d -exec /bin/chmod 755 {} \;
    - /bin/find $DEPLOYPATH -type f -exec /bin/chmod 644 {} \; 