---
deployment:
  tasks:
    # Define the deployment path
    - export DEPLOYPATH=/home3/avidityi/public_html/ghrproperties.id
    
    # Deploy the contents of /out directory directly to the document root
    - /bin/cp -R out/. $DEPLOYPATH
    
    # Make sure .htaccess is copied
    - /bin/cp .htaccess $DEPLOYPATH
    
    # Set file permissions
    - /bin/chmod 644 $DEPLOYPATH/.htaccess
    - /bin/find $DEPLOYPATH -type d -exec /bin/chmod 755 {} \;
    - /bin/find $DEPLOYPATH -type f -exec /bin/chmod 644 {} \; 