name: Build Next.js Static Export

# Workflow to automatically build and deploy Next.js static export
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

# Add permissions to allow the workflow to commit and push
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build Next.js static export
      run: npm run build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: static-build
        path: out/
        
    - name: Create .htaccess in build output
      run: cp .htaccess out/
      
    - name: Commit and push if changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add -f out/
        git commit -m "Build static export" || echo "No changes to commit"
        git push 