name: Deploy to Bluehost
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Bluehost
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.avidityid.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /public_html/ghrproperties.id
          port: 21
